---
title: "Welcome"
date: 2018-12-15
---
title: My GitHub Projects
author: Tamsamani
email: tamsmoha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some of my Projects lited here publically, you can brows them
  You can for and edit it whenever you like, happy to know about what's
  you make by this changes.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
